// List every bank file here. Each bank is a .js file that pushes one object into window.QUIZ_BANKS
// (see ../README.md for the schema). Plain script tags keep the app working from file:// without a server.
window.QUIZ_BANK_FILES = [
  "jetson-orin-thor-metrics__00-platforms.js",
  "jetson-orin-thor-metrics__A1-fp-int-pipe-interleaving.js",
  "jetson-orin-thor-metrics__A2-cuda-core-ceilings.js",
  "jetson-orin-thor-metrics__A3-tensor-core-ceilings.js",
  "jetson-orin-thor-metrics__A4-nvfp4-ceiling.js",
  "jetson-orin-thor-metrics__A5-l1-bandwidth-ceiling.js",
  "jetson-orin-thor-metrics__A6-bandwidth-vs-footprint.js",
  "jetson-orin-thor-metrics__A7-latency-landmarks.js",
  "jetson-orin-thor-metrics__B1-copy-engine-dram-direction.js",
  "jetson-orin-thor-metrics__B2-cache-level-interference.js",
  "jetson-orin-thor-metrics__B3-matrix-profile-stall-decomposition.js",
  "jetson-orin-thor-metrics__B4-gemm-victim-interference.js",
  "jetson-orin-thor-metrics__B5-tensor-under-cpu-contention.js",
  "jetson-orin-thor-metrics__B6-cotenancy-interference-matrix.js",
  "jetson-orin-thor-metrics__B7-aggregate-throughput.js",
  "jetson-orin-thor-metrics__B8-cotenancy-real-shape-mix-ladder.js",
  "jetson-orin-thor-metrics__C1-pi05-solo-latency.js",
  "jetson-orin-thor-metrics__C2-cotenancy-under-gpu-load.js",
  "jetson-orin-thor-metrics__L4-scheduling-ladder.js",
  "nvidia-gpu-anatomy__00-the-big-picture.js",
  "nvidia-gpu-anatomy__01-sm-and-smsp.js",
  "nvidia-gpu-anatomy__02-threads-warps-blocks-grids.js",
  "nvidia-gpu-anatomy__03-occupancy-and-registers.js",
  "nvidia-gpu-anatomy__04-cuda-cores-vs-tensor-cores.js",
  "nvidia-gpu-anatomy__05-memory-hierarchy.js",
  "nvidia-gpu-anatomy__06-caches-and-working-sets.js",
  "nvidia-gpu-anatomy__07-sharing-the-gpu.js",
  "nvidia-gpu-anatomy__08-measuring-a-gpu.js",
];
